version: '3.8'

services:
  frontend:
    build:
      context: ./registration-mern-app-badhaan
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./registration-server-Badhaan
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/budhan-users
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: